version: '3'
services:
  mysql:
    container_name: $TOJ_DB_CONTAINER_NAME
    ports:
      - $TOJ_DB_PORT:3306
    build:
      context: $PWD/docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=$TOJ_DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$TOJ_DB_NAME
    volumes:
      - $PWD/docker/mysql/conf:/etc/mysql/conf.d
      - $TOJ_DB_FILE_PATH:/var/lib/mysql
  app:
    privileged: true  # for docker in docker
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql:mysql
    # command: "sh entrypoint.sh 3000 0.0.0.0 /toj"
    command: "bundle exec rails s"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
#    volumes:
#      - .:/workdir # ソースコード変更したらDocker側も即反映されるように
