version: '2'
services:
  mysql:
    container_name: $TOJ_DB_CONTAINER_NAME
    env_file: .env
    ports:
      - $TOJ_DB_PORT:3306
    build:
      context: $PWD/docker/mysql
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=$TOJ_DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$TOJ_DB_NAME
    volumes:
      - $PWD/docker/mysql/conf:/etc/mysql/conf.d
      - $TOJ_DB_FILE_PATH:/var/lib/mysql
  app:
    privileged: true  # for docker in docker
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    links:
      - mysql:mysql
    command: "bash entrypoint.sh 3000 0.0.0.0"
    tty: true
    stdin_open: true
    ports:
      - 80:3000  # Port of TOJWebapp (default: 80)
    volumes:
      - $TOJ_FILE_DIR:/data
