# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5914656a71acb0fe392bf788491fa7603a47757bd09bb66e30542922b8defe5448b7546de81329050c7988f61762eeff1ce6aecdb0937ff780898df2f70561bf

test:
  secret_key_base: fb0a317e72b09ad7db318c403e7f0f23921d17094a9e215d02b86da47003dd03bce671ff66d0180c3209b00c132e9ab4340254c8486d9f567d3091a16bb27083

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
